name: newsbytes
description: Progscrape client for android and more.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  get: ^4.6.5
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
